// Flags in format (offset_from_base_address, bit)
#define CELIA_TEXT_AFTER_GETTING_OSHUS_SWORD 0x0, 0x2
#define COMPLETED_OSHUS_SWORD_TUTORIAL 0x0, 0x4
#define TALKED_TO_BARTENDER_ABOUT_LINEBECK 0x0, 0x8
#define TALKED_TO_OSHUS_AFTER_SEEING_RED_CHU_CHUS 0x0, 0x20
#define SHOWED_LINEBECK_SW_SEA_CHART 0x0, 0x40
#define SET_SAIL_FOR_THE_FIRST_TIME 0x0, 0x80
#define MERCAY_BRIDGE_REPAIRED 0x2, 0x2
#define TALKED_TO_OSHUS_FIRST_TIME 0x18, 0x2
#define SAW_BROKEN_MERCAY_BRIDGE_FIRST_TIME 0x2c, 0x1
#define UNCHARTED_ISLAND_BRIDGE_EXTENDED 0x26, 0x10
