#include "_flags.h"
#include "rando_settings.h"

#define NO_SETTING -1, 0

Flag flags[] = {
    {0x0, 0x2, NO_SETTING},  // CELIA_TEXT_AFTER_GETTING_OSHUS_SWORD
    {0x0, 0x4, NO_SETTING},  // COMPLETED_OSHUS_SWORD_TUTORIAL
    {0x0, 0x8, NO_SETTING},  // TALKED_TO_BARTENDER_ABOUT_LINEBECK
    {0x0, 0x20, NO_SETTING}, // TALKED_TO_OSHUS_AFTER_SEEING_RED_CHU_CHUS
    {0x0, 0x40, NO_SETTING}, // SHOWED_LINEBECK_SW_SEA_CHART
    {0x0, 0x80, NO_SETTING}, // SET_SAIL_FOR_THE_FIRST_TIME
    {0x2, 0x2, MERCAY_BRIDGE_REPAIRED_FROM_START}, // MERCAY_BRIDGE_REPAIRED
    {0x18, 0x2, NO_SETTING},                       // TALKED_TO_OSHUS_FIRST_TIME
    {0x2c, 0x1, NO_SETTING},  // SAW_BROKEN_MERCAY_BRIDGE_FIRST_TIME
    {0x26, 0x10, NO_SETTING}, // UNCHARTED_ISLAND_BRIDGE_EXTENDED
};
