name: pre-commit autoupdate

on:
  schedule:
  - cron: 0 0 1 * *  # first day of the month
  workflow_dispatch:

jobs:
  pre-commit-autoupdate:
    name: Update pre-commit hooks
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
          python-version-file: '.python-version'
          check-latest: true

    - name: Upgrade `pip`
      run: python -m pip install --upgrade pip

    - name: Install pre-commit
      run: pip install pre-commit

    - name: Update pre-commit hooks
      run: pre-commit autoupdate

    - name: Open a pull request
      uses: peter-evans/create-pull-request@v5
      with:
        add-paths: .pre-commit-config.yaml
        commit-message: '[pre-commit] automatic update'
        title: '[pre-commit] automatic update'
        body: ''
