ITEMS = {
    "small_key": 0x1,
    "small_green_rupee": 0x2,
    "oshus_sword": 0x3,
    "wooden_shield": 0x4,
    "bombs": 0x7,
    "bow": 0x8,
    "big_green_rupee": 0x9,
    "heart_container": 0xA,
    "boomerang": 0xC,
    "shovel": 0xD,
    "bombchus": 0xE,
    "boss_key": 0xF,
    "sw_sea_chart": 0x13,
    "nw_sea_chart": 0x14,
    "se_sea_chart": 0x15,
    "ne_sea_chart": 0x16,
    "small_blue_rupee": 0x18,
    "small_red_rupee": 0x19,
    "big_red_rupee": 0x1A,
    "big_gold_rupee": 0x1B,
    "hammer": 0x1F,
    "grappling_hook": 0x20,
    "fishing_rod": 0x24,
    "cannon": 0x25,
    "sun_key": 0x26,
    "quiver_upgrade": 0x28,
    "king_key": 0x2C,
    "power_gem": 0x2D,
    "wisdom_gem": 0x2E,
    "courage_gem": 0x2F,
    "common_treasure": 0x86,  # TODO: figure out difference between this and 0x7D
}
